baseURL = "http://growinggreentrees.net/"
languageCode = "en-us"
title = "Home"
theme = "growinggreen"
enableRobotsTXT = true
disableKinds = ["taxonomy", "taxonomyTerm"]
[params]
  author = "Presence Web Services"
  description = "Arborist offering healthy, educated solutions to any aspect of your landscape. Our tree service is available all seasons. Our tree care services include trimming, removal, planting, and plant health care. We are located in Redgranite, Wisconsin, but our service areas include Oshkosh, Omro, Winneconne, Berlin, Wautoma, and much more."
[markup.goldmark.renderer]
  unsafe= true
