baseURL = "http://growinggreentrees.net/"
languageCode = "en-us"
title = "Home"
theme = "growinggreen"
enableRobotsTXT = true
disableKinds = ["taxonomy", "taxonomyTerm"]
[params]
  author = "Presence Web Services"
  description = "Serving Oshkosh, Omro, Winneconne, Berlin, Redgranite, Wautoma, and surrounding areas of Wisconsin. We offer planting, trimming, removal, injection and other services."
[markup.goldmark.renderer]
  unsafe= true
